// Side-effect imports: each file registers itself in the catalog
import './buscar-cliente'
import './buscar-producto'
import './ver-factura-pdf'
import './ver-presupuesto-pdf'
import './enviar-email-presupuesto'
import './enviar-email-factura'
import './ver-servicio'
import './orden-servicio-pdf'
import './enviar-whatsapp'
import './clientes-por-zona'
import './segmentar-clientes'
import './ver-listas-email'
import './crear-lista-clientes'
import './enviar-email'
import './enviar-campana'
import './estado-campana'
import './marcar-vencimiento'
