// Side-effect imports: each file registers itself in the catalog
import './presupuestos-pendientes'
import './presupuestos-vencidos'
import './facturas-impagas'
import './facturas-hoy'
import './stock-bajo'
import './ventas-dia'
import './ventas-semana'
import './servicios-recientes'
import './servicios-pendientes'
import './resumen-matutino-ventas'
import './vencimientos-proximos'
import './vencimientos-criticos'
import './clientes-que-consumen'
import './clientes-sin-contacto'
import './servicios-demorados'
import './seguimientos-vencidos'
import './clv-analytics'
